research_task:
  description: >
    Research the latest stock market news and developments related to: {topic}
    Focus on finding recent market movements, earnings reports, analyst ratings,
    company announcements, and any significant events that could impact stock prices.
    Include both positive and negative developments. Current year is 2025.
  expected_output: >
    A comprehensive list of 10 bullet points covering the most relevant and recent
    stock market information about {topic}, including price movements, financial news,
    analyst opinions, and market trends that investors should be aware of.
  agent: researcher
  output_file: output/research_report.md

analysis_task:
  description: >
    Based on the research report about {topic}, provide a comprehensive investment analysis
    with specific price targets. Analyze fundamental and technical aspects, evaluate current
    valuation, assess risk factors, and provide clear BUY/HOLD/SELL recommendation with
    precise entry points, profit-taking levels, and stop-loss prices. Include both
    short-term trading and long-term investment perspectives with specific price ranges.
  expected_output: >
    A detailed investment analysis report with specific price targets including:
    - Executive Summary with clear BUY/HOLD/SELL recommendation
    - Current Price Analysis and Fair Value Estimation
    - BUY ZONES: Specific price ranges for optimal entry points
    - SELL ZONES: Target prices for profit-taking (25%, 50%, 100% gains)
    - STOP-LOSS: Risk management price levels
    - Fundamental Analysis (strengths, weaknesses, financial health)
    - Technical Analysis (support/resistance levels, trend analysis)
    - Risk Assessment with quantified risk/reward ratios
    - Timeline: Short-term (3-6 months) and Long-term (1-2 years) price targets
    - Investment Strategy: Position sizing and portfolio allocation suggestions
    Format as a professional investment recommendation report with actionable price levels.
  agent: investment_analyst
  output_file: output/investment_analysis.md

translation_task:
  description: >
    Translate the investment analysis report about {topic} from English to Korean.
    Maintain all financial terminology accuracy, preserve the analytical structure,
    and ensure the Korean version is natural and professional for Korean investors.
    Keep all numerical data, percentages, and recommendations exactly as in the original.
    Use appropriate Korean financial terminology and maintain the professional tone
    throughout the document.
  expected_output: >
    A complete Korean translation of the investment analysis report including:
    - All sections translated with accurate financial terminology
    - Preserved numerical data and recommendations
    - Natural Korean language flow suitable for professional investors
    - Maintained document structure and formatting
    - Professional tone appropriate for Korean financial markets
  agent: translator
  output_file: output/investment_analysis_kr.md
